import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "../components/Nav";
import DarkMode from "@/components/DarkMode";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let cookie = cookies().get("mode");

  return (
    <html lang="en">
      <body
        className={
          cookie != undefined && cookie.value == "dark"
            ? `${inter.className} bg-gray-200 dark`
            : `${inter.className} bg-gray-200`
        }
      >
        <Nav></Nav>
        <main>{children}</main>
        <DarkMode />
      </body>
    </html>
  );
}
